table highQualVariants
"High-quality variants in SARS-CoV-2 from Galaxy pipeline"
    (
    string chrom;       "Reference sequence chromosome or scaffold"
    uint   chromStart;  "Start position in chromosome"
    uint   chromEnd;    "End position in chromosome"
    string name;        "Amino acid change"
    uint   score;       "Score from 0-1000 (might not be applicable)"
    char[1] strand;        "Defines the strand"
    uint thickStart;    "Starting position of the actual nucleotide change"
    uint thickEnd;      "End position of the actual nucleotide change"
    string nucChange;    "ref/alt"
    string function;    "Molecular consequence e.g. NON_SYNONYMOUS_CODING or CODON_DELETION"
    string gene;        "Gene in which mutation occurs"
    float medianAF;     "median of intra-sample allele frequencies observed for the variant"
    float q25AF;        "lower quartile of intra-sample allele frequencies observed for the variant"
    float q75AF;        "upper quartile of intra-sample allele frequencies observed for the variant"
    string lineage;     "pangolin-assigned lineage"
    float withinLineageFrequency; "frequency at which the variant has been observed among samples of this lineage"
    string earliestDateseen;      "collection date of the oldest sample from the lineage that the variant has been observed in"
    string earliestSampleseen;    "run accession of the oldest sample from the lineage that the variant has been observed in"
    string earliestCountryseen;   "country of collection of the oldest sample from the lineage that the variant has been observed in"
    string countries;             "comma-separated list of countries that the variant/lineage combination has been observed in"
    )
